services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    args:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    ports:
      - ${PORT}:${PORT}
    # command: >
    #   bash -c "python manage.py migrate --no-input &&
    #            gunicorn ajhome.wsgi:application --bind 0.0.0.0:${PORT} --workers 4"
    # volumes:
    #   - .:/app
    environment:
      PORT: ${PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      BASE_URL: ${BASE_URL}

