services:
  app:
    build: .
    # ports:
    #   - "8000:8000"
    command: >
      bash -c "python manage.py migrate --no-input &&
               gunicorn ajhome.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      BASE_URL: ${BASE_URL}